version: '3.7'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${COMPOSE_PROJECT}-mysql
    volumes: 
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - ${MYSQL_PORT}
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    networks:
      - akid
    
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./../:/app
    container_name: ${COMPOSE_PROJECT}-nginx
    restart: always
    ports:
      - ${WEB_PORT}:80
    networks:
      - akid  

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./../:/app
    container_name: ${COMPOSE_PROJECT}-php-fpm
    depends_on:
      - mysql
    networks:
      - akid  

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ./../:/app
    command: sleep 10000
    container_name: ${COMPOSE_PROJECT}-php-cli
    networks: 
      - akid
  
volumes:
  mysql_data:
networks:
    akid:
      name: akid        
